name = "payload-cloudflare-neon"
main = ".open-next/worker.js"
compatibility_date = "2025-10-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[observability]
enabled = true

[assets]
binding = "ASSETS"
directory = ".open-next/assets"
