name = "payload-better-auth-cloudflare-neon"
main = ".open-next/worker.js"
compatibility_date = "2025-10-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
keep_vars = true

[observability]
enabled = true

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "1ee75d62f0b942f9ae264831777e4c46"
localConnectionString = "postgresql://neon_user:neon_password@localhost:5432/neon_dev"
