services:
  postgres:
    image: postgres:17-alpine3.22
    container_name: neon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: neon_user
      POSTGRES_PASSWORD: neon_password
      POSTGRES_DB: neon_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_for_payload_better_auth_cloudflare_neon:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U neon_user -d neon_dev']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: neon-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neon.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    volumes:
      - pgadmin_data_for_payload_better_auth_cloudflare_neon:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data_for_payload_better_auth_cloudflare_neon:
    driver: local
  pgadmin_data_for_payload_better_auth_cloudflare_neon:
    driver: local
